---
language: python
python:
  - "3.7"
install:
  - pip install ansible-lint yamllint
script:
  - ansible-lint
  - yamllint -s .
notifications:
  webhooks:
    - 'https://galaxy.ansible.com/api/v1/notifications/'
