---
- name: ensure pihole ipv4 address variable is defined
  set_fact:
    pihole_serverip: "{{ ansible_default_ipv4.address }}"
  when:
    - pihole_serverip is not defined or not pihole_ip

- name: ensure pihole ipv6 address variable is defined
  set_fact:
    pihole_ip: "{{ ansible_default_ipv6.address }}"
  when:
    - pihole_ipv6
    - pihole_serveripv6 is not defined or not pihole_serveripv6
