---
- name: ensure pihole ipv4 address variable is defined
  set_fact:
    pihole_ip: "{{ ansible_default_ipv4.address }}"
  when:
    - pihole_ip is undefined or pihole_ip == ""

- name: ensure pihole ipv6 address variable is defined
  set_fact:
    pihole_ip: "{{ ansible_default_ipv6.address }}"
  when:
    - pihole_ipv6_support == "True"
    - pihole_ipv6 is undefined or pihole_ipv6 == ""

- name: ensure docker container with pihole is up and running
  docker_container:
    name: "pihole"
    image: "pihole/pihole:latest"
    state: "started"
    restart_policy: "unless-stopped"
    ports:
      - "{{ pihole_ip }}:53:53/udp"
      - "{{ pihole_ip }}:80:80/tcp"
    volumes:
      - "/pihole/pihole:/etc/pihole:rw"
      - "/pihole/dnsmasq.d:/etc/dnsmasq.d:rw"
    dns_servers:
      - 127.0.0.1
    env:
      ServerIP="{{ pihole_ip }}"
      ServerIPv6="{{ pihole_ipv6 }}"
      IPv6="{{ pihole_ipv6_support }}"
      WEBPASSWORD="{{ pihole_webpassword }}"
      TZ="{{ pihole_timezone }}"
  become: true
