---
- name: ensure pihole
  block:
    - import_tasks: environment.yml
    - import_tasks: group.yml
    - import_tasks: user.yml
    - import_tasks: directories.yml
    - import_tasks: docker.yml
  tags:
    - pihole
